DROPDOWN_LISTS = {'брюки': {'title': 'Выберите вариант',
           'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                        {'code': 'variants', 'name': 'Муж, Жен, Дет', 'group': 'male'}]},
 'свитер': {'title': 'Выберите вариант',
            'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                         {'code': 'variants', 'name': 'Взросл, Дет', 'group': 'child'}]},
 'шорты': {'title': 'Выберите вариант',
           'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                        {'code': 'variants', 'name': 'Муж, Жен, Дет', 'group': 'male'}]},
 'сумка': {'title': 'Выберите вариант',
           'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                        {'code': 'variants', 'name': 'Кожа, Пластик, Текстиль, Прочие', 'group': 'plastic'}]},
 'трусы': {'title': 'Выберите вариант',
           'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                        {'code': 'variants', 'name': 'Муж, Жен, Дет', 'group': 'male'}]},
 'куртка': {'title': 'Выберите вариант',
            'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                         {'code': 'variants', 'name': 'Муж, Жен, Дет', 'group': 'male'}]},
 'пиджак': {'title': 'Выберите вариант',
            'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                         {'code': 'variants', 'name': 'Муж, Жен, Дет', 'group': 'male'}]},
 'ремень': {'title': 'Выберите вариант',
            'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                         {'code': 'variants', 'name': 'Кожа, Пластик, Эластич', 'group': 'plastic'}]},
 'джинсы': {'title': 'Выберите вариант',
            'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                         {'code': 'variants', 'name': 'Муж, Жен, Дет', 'group': 'male'}]},
 'рубашка': {'title': 'Выберите вариант',
             'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                          {'code': 'variants', 'name': 'Муж, Жен, Дет', 'group': 'male'}]},
 'туфли': {'title': 'Выберите вариант',
           'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                        {'code': 'variants',
                         'name': 'Муж пластик, Жен пластик, Дет пластик, Муж кожа, Жен кожа, Дет кожа',
                         'group': 'plastic'}]},
 'винт': {'title': 'Выберите вариант',
          'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                       {'code': 'variants', 'name': 'Крест, Шест, Без головок', 'group': 'other'}]},
 'комплект одежды': {'title': 'Выберите вариант',
                     'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                                  {'code': 'variants', 'name': 'Муж, Жен, Дет', 'group': 'male'}]},
 'скатерть': {'title': 'Выберите вариант',
              'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                           {'code': 'variants', 'name': 'Хлопок, Синтетика', 'group': 'other'}]},
 'фигурка': {'title': 'Выберите вариант',
             'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                          {'code': 'variants', 'name': 'Пласт, Металл, Дерево', 'group': 'metal'}]},
 'насос': {'title': 'Выберите вариант',
           'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                        {'code': 'variants', 'name': 'Воздух, Вода, Топливо, Ручной', 'group': 'manual'}]},
 'держатель': {'title': 'Выберите вариант',
               'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                            {'code': 'variants', 'name': 'Пласт, Металл, Дерево', 'group': 'metal'}]},
 'выключатель': {'title': 'Выберите вариант',
                 'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                              {'code': 'variants', 'name': 'Кнопочный, Поворотный', 'group': 'other'}]},
 'переключатель': {'title': 'Выберите вариант',
                   'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                                {'code': 'variants', 'name': 'Кнопочный, Поворотный', 'group': 'other'}]},
 'рабочая обувь': {'title': 'Выберите вариант',
                   'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                                {'code': 'variants', 'name': 'Ботинки, Кроссовки, Босоножки', 'group': 'other'}]},
 'костюм классический': {'title': 'Выберите вариант',
                         'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                                      {'code': 'variants', 'name': 'Жен, Муж', 'group': 'male'}]},
 'коврик': {'title': 'Выберите вариант',
            'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                         {'code': 'variants', 'name': 'Пласт, Ворс', 'group': 'plastic'}]},
 'фара': {'title': 'Выберите вариант',
          'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                       {'code': 'variants', 'name': 'В сборе, Лампочка', 'group': 'other'}]},
 'кабель переходник': {'title': 'Выберите вариант',
                       'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                                    {'code': 'variants', 'name': 'Кабель, Адаптер, Зарядка', 'group': 'other'}]},
 'перчатки': {'title': 'Выберите вариант',
              'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                           {'code': 'variants', 'name': 'Перчатки, Хозяйственные', 'group': 'other'}]},
 'фильтр': {'title': 'Выберите вариант',
            'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                         {'code': 'variants', 'name': 'Вода, Воздух, Масло бензин', 'group': 'other'}]},
 'чайник': {'title': 'Выберите вариант',
            'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                         {'code': 'variants', 'name': 'Металл, Стекло, Электро', 'group': 'metal'}]},
 'стул': {'title': 'Выберите вариант',
          'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                       {'code': 'variants', 'name': 'Металл, Складной, Табурет, Вращающийся, Дерево', 'group': 'metal'}]},
 'мебель': {'title': 'Выберите вариант',
            'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                         {'code': 'variants', 'name': 'Металл, Дерево, Пластик', 'group': 'metal'}]},
 'брелок': {'title': 'Выберите вариант',
            'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                         {'code': 'variants', 'name': 'Пласт, Металл, Дерево, Стекло', 'group': 'metal'}]},
 'ведро': {'title': 'Выберите вариант',
           'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                        {'code': 'variants', 'name': 'Пласт, Металл, Дерево', 'group': 'metal'}]},
 'емкость': {'title': 'Выберите вариант',
             'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                          {'code': 'variants', 'name': 'Пласт до 2л, Металл, Стекло', 'group': 'metal'}]},
 'чашка': {'title': 'Выберите вариант',
           'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                        {'code': 'variants', 'name': 'Керамика, Стекло, Пластик', 'group': 'plastic'}]},
 'кружка': {'title': 'Выберите вариант',
            'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                         {'code': 'variants', 'name': 'Керамика, Стекло, Пластик', 'group': 'plastic'}]},
 'канцеляр': {'title': 'Выберите вариант',
              'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                           {'code': 'variants', 'name': 'Пластик, Металл, Бумага', 'group': 'metal'}]},
 'клапан': {'title': 'Выберите вариант',
            'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                         {'code': 'variants', 'name': 'Обратный, Поплавковый, Электро', 'group': 'electric'}]},
 'пижама': {'title': 'Выберите вариант',
            'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                         {'code': 'variants', 'name': 'Жен, Муж', 'group': 'male'}]},
 'кулинарная форма': {'title': 'Выберите вариант',
                      'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                                   {'code': 'variants', 'name': 'Пласт, Металл, Керамика', 'group': 'metal'}]},
 'фитинг': {'title': 'Выберите вариант',
            'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                         {'code': 'variants', 'name': 'Металл, Пластик', 'group': 'metal'}]},
 'ваза': {'title': 'Выберите вариант',
          'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                       {'code': 'variants', 'name': 'Керамика, Стекло', 'group': 'glass'}]},
 'кашпо': {'title': 'Выберите вариант',
           'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                        {'code': 'variants', 'name': 'Керамика, Стекло', 'group': 'glass'}]},
 'кошелек': {'title': 'Выберите вариант',
             'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                          {'code': 'variants', 'name': 'Пластик, Кожа, Текстиль', 'group': 'plastic'}]},
 'картхолдер': {'title': 'Выберите вариант',
                'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                             {'code': 'variants', 'name': 'Пластик, Кожа', 'group': 'plastic'}]},
 'крепеж': {'title': 'Выберите вариант',
            'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                         {'code': 'variants', 'name': 'Пласт, Металл, Фурнитура', 'group': 'metal'}]},
 'пуговицы': {'title': 'Выберите вариант',
              'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                           {'code': 'variants', 'name': 'Пластик, Металл', 'group': 'metal'}]},
 'футляр': {'title': 'Выберите вариант',
            'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                         {'code': 'variants', 'name': 'Пластик, Кожа, Авто, Пласт', 'group': 'plastic'}]},
 'хомут': {'title': 'Выберите вариант',
           'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                        {'code': 'variants', 'name': 'Пластик, Металл, Резина', 'group': 'metal'}]},
 'посуда': {'title': 'Выберите вариант',
            'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                         {'code': 'variants', 'name': 'Керамика, Стекло, Пластик, Металл, Пленка, Пластик', 'group': 'metal'}]},
 'накладка': {'title': 'Выберите вариант',
              'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                           {'code': 'variants', 'name': 'Пласт, Металл, Резина, Пленка', 'group': 'metal'}]},
 'замок': {'title': 'Выберите вариант',
           'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                        {'code': 'variants', 'name': 'Висячий, Авто, Врезной, Уплотнитель', 'group': 'other'}]},
 'кран': {'title': 'Выберите вариант',
          'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                       {'code': 'variants', 'name': 'Смеситель, Шаровой, Электро', 'group': 'electric'}]},
 'корзина': {'title': 'Выберите вариант',
             'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                          {'code': 'variants', 'name': 'Пластик, Текстиль, Металл', 'group': 'metal'}]},
 'органайзер': {'title': 'Выберите вариант',
                'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                             {'code': 'variants', 'name': 'Пластик, Текстиль, Чехол пласт', 'group': 'plastic'}]},
 'контейнер': {'title': 'Выберите вариант',
               'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                            {'code': 'variants', 'name': 'Пластик, Текстиль, Чехол пласт, Неткан', 'group': 'plastic'}]},
 'салфетк': {'title': 'Выберите вариант',
             'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                          {'code': 'variants', 'name': 'Бумажные, Микрофибра, Неткан, Влажные, Хлопок, Синтет', 'group': 'textile'}]},
 'часы': {'title': 'Выберите вариант',
          'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                       {'code': 'variants', 'name': 'Наручные, Электронные, Настенные, Смарт', 'group': 'electric'}]},
 'чехол': {'title': 'Выберите вариант',
           'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                        {'code': 'variants', 'name': 'Для телефон, На сиденье, Тент, Металл, Пластик, Дивандек', 'group': 'metal'}]},
 'шкатулка': {'title': 'Выберите вариант',
              'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                           {'code': 'variants', 'name': 'Пластик, Дерево, Металл, Текстиль', 'group': 'metal'}]},
 'ремешок': {'title': 'Выберите вариант',
             'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                          {'code': 'variants', 'name': 'Пластик, Кожа, Металл', 'group': 'metal'}]},
 'тарелка': {'title': 'Выберите вариант',
             'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                          {'code': 'variants', 'name': 'Керамика, Стекло, Пластик, Металл, Дерево', 'group': 'metal'}]},
 'значок': {'title': 'Выберите вариант',
            'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                         {'code': 'variants', 'name': 'Пласт, Металл, Бижут, Стекл', 'group': 'metal'}]},
 'губка': {'title': 'Выберите вариант',
           'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                        {'code': 'variants', 'name': 'Пласт, Металл', 'group': 'metal'}]},
 'ложка': {'title': 'Выберите вариант',
           'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                        {'code': 'variants', 'name': 'Столовая, Металл, Дерево', 'group': 'metal'}]},
 'матрас': {'title': 'Выберите вариант',
            'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                         {'code': 'variants', 'name': 'Прочий, Надувной', 'group': 'other'}]},
 'ящик для хранения': {'title': 'Выберите вариант',
                       'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                                    {'code': 'variants', 'name': 'Пласт, Текстиль, Быт пластик', 'group': 'plastic'}]},
 'велосипед': {'title': 'Выберите вариант',
               'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                            {'code': 'variants', 'name': 'Взрослый, Детский', 'group': 'child'}]},
 'крючок': {'title': 'Выберите вариант',
            'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                         {'code': 'variants', 'name': 'Пласт, Металл одежд, Металл', 'group': 'metal'}]},
 'мешки': {'title': 'Выберите вариант',
           'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                        {'code': 'variants', 'name': 'Зип, Пылесос, Прочие', 'group': 'other'}]},
 'мешок': {'title': 'Выберите вариант',
           'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                        {'code': 'variants', 'name': 'Зип, Пылесос, Прочие', 'group': 'other'}]},
 'совок': {'title': 'Выберите вариант',
           'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                        {'code': 'variants', 'name': 'Пласт, Металл', 'group': 'metal'}]},
 'адаптер': {'title': 'Выберите вариант',
             'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                          {'code': 'variants', 'name': 'Переход, Беспровод, Прочие', 'group': 'other'}]},
 'ключ': {'title': 'Выберите вариант',
          'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                       {'code': 'variants', 'name': 'Неразвод, Развод, Авто', 'group': 'other'}]},
 'шланг': {'title': 'Выберите вариант',
           'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                        {'code': 'variants', 'name': 'Рез без фит, Рез с фит, Пластик', 'group': 'plastic'}]},
 'трубка': {'title': 'Выберите вариант',
            'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                         {'code': 'variants', 'name': 'Рез без фит, Рез с фит, Пластик', 'group': 'plastic'}]},
 'диспенсер': {'title': 'Выберите вариант',
               'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                            {'code': 'variants', 'name': 'Пласт до 2, Металл, Пласт после 2', 'group': 'metal'}]},
 'покрышка': {'title': 'Выберите вариант',
              'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                           {'code': 'variants', 'name': 'Машин, Мото, Вело, Рыболовный', 'group': 'other'}]},
 'шина': {'title': 'Выберите вариант',
          'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                       {'code': 'variants', 'name': 'Машин, Мото, Вело, Текстиль', 'group': 'textile'}]},
 'фурнитур': {'title': 'Выберите вариант',
              'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                           {'code': 'variants', 'name': 'Мебель, Одежда, Текстиль', 'group': 'textile'}]},
 'электроинструмент': {'title': 'Выберите вариант',
                       'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                                    {'code': 'variants',
                                     'name': 'Воздуход, Пила, Пласт после 2, Триммер, Шлифов, Снег, Аккум',
                                     'group': 'plastic'}]},
 'щетка': {'title': 'Выберите вариант',
           'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                        {'code': 'variants', 'name': 'Для дома, Части машин, Вело, Металл', 'group': 'metal'}]},
 'пакет': {'title': 'Выберите вариант',
           'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                        {'code': 'variants', 'name': 'Зип, Пылесос, Вело, Прочие', 'group': 'other'}]},
 'канистра': {'title': 'Выберите вариант',
              'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                           {'code': 'variants', 'name': 'Пласт до 2, Металл, Пласт после 2', 'group': 'metal'}]},
 'бак': {'title': 'Выберите вариант',
         'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                      {'code': 'variants', 'name': 'Пласт до 2, Металл, Пласт после 2', 'group': 'metal'}]},
 'флакон': {'title': 'Выберите вариант',
            'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                         {'code': 'variants', 'name': 'Пласт до 2, Металл, Пласт после 2', 'group': 'metal'}]},
 'полка': {'title': 'Выберите вариант',
           'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                        {'code': 'variants', 'name': 'Металл, Дерево, Пластик, Прочие', 'group': 'metal'}]},
 'стеллаж': {'title': 'Выберите вариант',
             'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                          {'code': 'variants', 'name': 'Металл, Дерево, Пластик, Пласт после 2', 'group': 'metal'}]},
 'шкаф': {'title': 'Выберите вариант',
          'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                       {'code': 'variants', 'name': 'Металл, Дерево, Пластик, Пласт после 2', 'group': 'metal'}]},
 'диван': {'title': 'Выберите вариант',
           'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                        {'code': 'variants', 'name': 'Металл, Дерево, Пластик, Пласт после 2', 'group': 'metal'}]},
 'кровать': {'title': 'Выберите вариант',
             'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                          {'code': 'variants', 'name': 'Металл, Дерево, Пластик, Пласт после 2', 'group': 'metal'}]},
 'бокал': {'title': 'Выберите вариант',
           'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                        {'code': 'variants', 'name': 'Керамика, Стекло, Пластик', 'group': 'plastic'}]},
 'короб': {'title': 'Выберите вариант',
           'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                        {'code': 'variants', 'name': 'Пласт, Текстиль, Металл', 'group': 'metal'}]},
 'бутылка': {'title': 'Выберите вариант',
             'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                          {'code': 'variants', 'name': 'Пласт до 2, Металл, Пласт после 2, Стекло, Хлопок, Синтет', 'group': 'metal'}]},
 'ящик': {'title': 'Выберите вариант',
          'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                       {'code': 'variants', 'name': 'Пласт, Текстиль, Металл, Прочие', 'group': 'metal'}]},
 'тряпк': {'title': 'Выберите вариант',
           'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                        {'code': 'variants', 'name': 'Бумажные, Микрофибра, Неткан, Прочие', 'group': 'textile'}]},
 'таз': {'title': 'Выберите вариант',
         'variants': [{'code': 'title', 'name': 'Выберите вариант', 'group': 'other'},
                      {'code': 'variants', 'name': 'Пласт, Металл', 'group': 'metal'}]}}